### ISSUE TITLE
Update the links in the README file

### ISSUE THREAD

**Issue by garaud** [dimitri/cl-abnf#1]
Hi,

The links to RFC2234 and cl-ppcre are wrong (nice Github 404!). I can read
`[http://tools.ietf.org/html/rfc2234](RFC2234)` in the README.md file instead of `[RFC2234](http://tools.ietf.org/html/rfc2234)`. I'm also confused when I write links in Markdown or Org-mode.

Cheers,
Damien

**Comment by dimitri** [comment]
Thanks!
