### ISSUE TITLE
Phooey on no recursive grammar rules.

### ISSUE THREAD

**Issue by heegaiximephoomeeghahyaiseekh** [dimitri/cl-abnf#3]
I tried to create a grammar for a programming language, only to get the error
"Can not expand recursive rule: ABNF-EXPRESSION."

In any programming language, expressions necessarily have a recursive grammar,  because
expressions can contain subexpressions which have the same grammar as the original expression. Without the ability to handle recursive grammars, ABNF cannot be used to parse the source code of any programming language.

**Comment by dimitri** [comment]
Indeed, you're right, which is why the second sentence of the README file reads: _The generated parser is a regular expression scanner provided by the `cl-ppcre` lib, which means that we can't parse recursive grammar definition_.
